### ISSUE TITLE
umbrella is convenience in case for rain

### ISSUE THREAD

**Issue by pankona** [pankona/pankona.github.com#107]
雨が降ったら傘をさすと便利

梅雨になったら雨がいっぱい降るんだけど、傘をさすと濡れなくて便利。

ところで shupatto というメーカーが出している傘があって、これはどうも閉じるときに留め具を使わなくていいらしい。
https://marna.jp/product/s498/

傘を閉じるときにきっちり閉じようと思うと、くるくるって巻く必要があって左手がびちゃびちゃになるっていう一面があるよね。そもそも雨ってそんなに清潔じゃない気もするし、できれば雨で濡れた傘って触りたくない。あれが起こらないっていうのは結構文明開化なんじゃないかっていう気がする。

傘ってすごい盗まれるもんだと思っていて (たまたま自分ちの周りがスラム街みたいな治安なのかもしれないが)、その点、この傘はちょっとお値打ちなので買うかどうか迷っちゃうわね。あと自分は結構電車の中に置き忘れるみたいなことも多いので、あわせて「なくさない仕組み」を入れられたら買ってもいいかなーなんて思っておるところ。

これがあれば雨の日のお出かけもウキウキ気分かもしれないね！

**Comment by kachick** [comment]
僕が書いたポエムもデプロイされるようにしてほしい

**Comment by pankona** [comment]
ダメです

**Comment by pankona** [comment]
動作確認のためリオープン

**Comment by pankona** [comment]
まずはラベルなしでイシューを編集。プルリクが作られないのが期待値

**Comment by kachick** [comment]
https://github.com/pankona/pankona.github.com/pull/127 の動作確認

article ラベル無: ✅ - https://github.com/pankona/pankona.github.com/actions/runs/5244792896
article ラベル有: ?? -

**Comment by pankona** [comment]
article がカテゴリとして扱われることもなかった

**Comment by pankona** [comment]
デプロイも済み。完璧では！！

**Comment by pankona** [comment]
色々変えたのでもっかい動作確認をしていく

**Comment by pankona** [comment]
動いたので yoshi
