### ISSUE TITLE
dev-env-using-codespaces-and-copilot

### ISSUE THREAD

**Issue by pankona** [pankona/pankona.github.com#196]
タブレットでコード書ける？GitHub CodespacesとCopilotで試してみた

さあ、今日は楽ちん開発環境のお話よ。最近の開発界隈っていろんな便利ツールが出てきて、ちょっとした時間でもすぐにコーディングができるようになったわよね。

## CopilotとChatGPTで手軽に

まず、GitHub CopilotやChatGPTなんかは、素早くコードを生成してくれるから、スキマ時間でもずいぶんと作業が進むのよ。これらが全部入りの開発環境に組み込まれてたら、もう手が止まらないわ！

## GitHub Codespacesって何？

それで、GitHub Codespacesがあるの。これはVSCodeをベースにしたCloud IDEなのよ。VSCodeは得意じゃない人もいるけど、Copilotとの相性は抜群なのよね。

実際、[こちらのリポジトリ](https://github.com/pankona/generic-defence-game)でCodespacesを試してみたわけ。目標は「タブレットで開発できるか？」なんだけどね。

## 何をやったの？

- CopilotなどのVSCode extensionをプリインストール
- Codespacesが立ち上がると、自動でairも立ち上がって、ソースが変更されると自動ビルド
- wasmで作成したものをサーブして、ビルド後にブラウザをリロードすると変更が確認できる状態に

## タブレットでの現実

でもね、現実的にはタブレットだけで開発するのはちょっと厳しいわ。Copilotを使っても、AIとおしゃべりするためにはキーボード入力が必要だし、特定のコードを選択する動作も多いから、ポインティングデバイスが必須よ。

## それでも便利

でも、GitHubのUIでコードをいじるよりは、Codespacesを使った方が全然便利。IDEの機能もフルに使えるし、wasmでサービスしてるから、変更のプレビューも確認できる。

## まとめ

- Codespacesでタブレットも対応した開発環境を目指した
  - Copilotとwasmを活用し、自動ビルド機能も
- タブレットだけでの開発は厳しいが、普通に便利

というわけ。もしこれから何か新しいプロジェクトを始めるなら、CodespacesとCopilot、それにwasmを使って、ちょっとした時間でも効率よく開発してみてはどうかしら。それじゃ、また次回！

**Comment by pankona** [comment]
くっそ長文なこだわりのプロンプトを ChatGPT に一撃食わせてブログ記事を生成するチャレンジ

**Comment by pankona** [comment]
言いようのないダメさを感じる

**Comment by pankona** [comment]
ここまで書いといてもらった上で、こっからさらに codespaces を起動して AI と推敲を重ねるのがいいのかもしれない (意地でも自分で書こうとしないスタイル)

**Comment by pankona** [comment]
文を何度も読むうちに腹が立ってきた

**Comment by pankona** [comment]
「意地でも自分で文章を書かないブログ記事執筆」みたいなほうがフィットする気がしてきた。いったんこの記事はボツにします。 @kachick レビュー感謝

**Comment by pankona** [comment]
まずもって口調が腹立たしい

**Comment by kachick** [comment]
今、ChatGPTに過去のパン粉ブログを食わせながらなんとか書き直させようと試してみてたけど特に改善は見られなかった。あふれる加齢臭が中々醸せない

**Comment by pankona** [comment]
もう手が止まらないわ！
そんなこと俺は一文字も書いてないぞ

**Comment by pankona** [comment]
っていうか手が止まらないことは求めてないんだよな。むしろ手数を少なくしようって話なんだからな

**Comment by kachick** [comment]
ChatGPT 3.5 でいくらやっても暖簾に腕押しだったけど、 Edge から使える GPT4 だと一発で結構良いのが出てきたよ
特に文体とか語調みたいな特徴を引っ張ってくる部分の精度が段違いだった

```markdown
タブレットで開発できるのか？GitHub CodespacesとCopilotで挑戦してみた
under プログラミング

タブレットで開発できるのか？ということで 2023 年 10 月から GitHub Codespaces と Copilot を使ってみることにした。最近の開発界隈はいろんな便利ツールが出てきて、どこでもコーディングができるようになったらしい。それは本当なのか？

## CopilotとChatGPTで楽々

まず、CopilotやChatGPTはAIがコードを生成してくれるツールだ。これらがあれば、コーディングの手間が減って、スキマ時間でも作業が進むはずだ。しかも、これらはVSCodeに組み込まれているから、IDEの機能も使える。

## GitHub Codespacesって何？

次に、GitHub Codespacesだ。これはVSCodeをベースにしたCloud IDEだ。VSCodeは好き嫌いが分かれるけど、Copilotとの相性は抜群だ。

実際、こちらのリポジトリでCodespacesを使ってみた。目標は「タブレットで開発できるか？」だ。

## どうやったの？

- CopilotなどのVSCode extensionをプリインストール
- Codespacesが立ち上がると、自動でairも立ち上がって、ソースが変更されると自動ビルド
- wasmで作成したものをサーブして、ビルド後にブラウザをリロードすると変更が確認できる状態に

## タブレットだけでは無理

でもね、正直なところ、タブレットだけでは開発するのは無理だった。Copilotを使っても、AIとおしゃべりするためにはキーボード入力が必要だし、特定のコードを選択する動作も多いから、ポインティングデバイスが必須だ。

## それでも便利

でも、GitHubのUIでコードをいじるよりは、Codespacesを使った方が全然便利だった。IDEの機能もフルに使えるし、wasmでサービスしてるから、変更のプレビューも確認できる。

## まとめ

- CodespacesとCopilotでタブレットでも開発できるようにした
  - Copilotとwasmを活用し、自動ビルド機能も
- タブレットだけでは開発は厳しいけど、便利なツールはある

というわけ。もしあなたもタブレットで開発してみたいなら、CodespacesとCopilot、それにwasmを使ってみてはどうかしら。それじゃ、またね！

```

**Comment by pankona** [comment]
おおー、だいぶマシな気がする…。わいも GPT4 (oepnapi のやつ) を使っているんだけどな。ちょっと違うのかな
