### ISSUE TITLE
try-coderabbit

### ISSUE THREAD

**Issue by pankona** [pankona/pankona.github.com#204]
CodeRabbit をブログリポジトリ入れてみる

https://coderabbit.ai という、AI のちからでコードレビューを勝手にやってくれるというサービスが登場していたので試してみる。このブログでだ。

自分が書いているこのブログサイトは以下の流れで記事が作られている。
- issue を立てて article ラベルを貼り付ける
- 自動的に issue の内容をちょいといい感じに整形した pull request が作成される
- マージすればブログ記事が公開される

スマホでも記事が書きたいし PC でも記事が書きたいし、せっかく GitHub pages でブログやってるんだからそれになんかいい感じ乗っかって楽ができないかなーと思って構築したのがこの仕組みである。スマホだけでも GitHub で issue を書きさえすればブログ記事が書けるってのはなかなか便利である (便利ではあるが別に記事が量産されるかというとそれは別の話ではある)。

で、つまり記事が出ていく過程で pull request が一度生成されるようになっているわけで、先述の CodeRabbit さんに「ブログ記事を公開する前にいっちょレビューしてもらえる」って話ならば、なかなかもしかして便利で面白いのではないかと思ったわけである。

CodeRabbit の導入はとても簡単で、5分もあれば所望のリポジトリに CodeRabbit を導入することができた。お値段は、Open Source (Public Repository) ならば無料で使いたい放題らしい。ほんまか？大丈夫か？

公式ドキュメントはこちら https://coderabbit.ai/docs/introduction/
導入方法なども紹介されていてたいへん親切であった。これでとても便利だったらとても嬉しい。

---

さて、本記事に対応する pull request は https://github.com/pankona/pankona.github.com/pull/205 である。
ここを見ると CodeRabbit がどんなようなことを言ってくれるものであるかなんとなく察することができるかと思う。

![image](https://github.com/pankona/pankona.github.com/assets/6533008/1c6110e7-c182-493b-9183-f211233ef74a)

![image](https://github.com/pankona/pankona.github.com/assets/6533008/12d8481e-7fe8-49dc-9d19-5042399d0803)

変更の概要をコメントしてくれたり、あと謎のポエム？もつけてくれるようだ。文章のどこがおかしいとかもっとこうしたほうが読みやすいとか言ってくれたら嬉しかったが、そこまではしてくれない？ようだ (日本語だしソースコードじゃないってこともあろうか)。あんまり便利でもないがひとまず邪魔ではないので、いったん入れたままで様子を見てみようと思う。

ちなみに設定項目は Web の UI からぽちぽちいじってもいいし、リポジトリのてっぺんに `.coderabbit.yaml` を置いといても見てくれるようだ。たくさんのリポジトリに導入しようと思ったら設定ファイルを使うほうが便利そうね。

---

記事を何度か書き直している途中で Rate Limit に達してしまって CodeRabbit さんが動かなくなってしまった。一時間単位で Rate Limit が設定されているようなのでほっとけばまた動いてくれるのだと思う。とはいえそんなにヘビーにレビューをお願いしているわけでもないのにあっさり Rate Limit に達してしまうところを見るにつけては、一通り書き終わったところで一発レビューをお願いする (自動でレビューさせない) という使い方のほうがいいのかもしれない。

スラッシュコマンド (dependabot を操作するのと同じようなやり口) でレビューの依頼ができるみたいなので、WIP が外れるところで一発 `@coderabbit review` みたいに書いてみるのが丸いやり方かしらね。

**Comment by kachick** [comment]
💭 AI の微妙にずれたレビューコメントに一つ一つ丁寧に~反論~返事しているとパワハラ味が出てきて嫌オブ嫌

https://github.com/pankona/pankona.github.com/pull/245#issuecomment-1927247917
https://github.com/pankona/pankona.github.com/pull/254#issuecomment-1945352031

**Comment by kachick** [comment]
初期の response code に対するレビューがすごい良かったもののその後メリットを感じたことがなく、どうも変だなとオフィシャルサイト覗いてみると response code に対するレビューがまさに代表例として挙げられている。ので、実質そういう linter なのかもしんない

![image](https://github.com/user-attachments/assets/8ba77305-2a2c-4c9f-b7ad-7398290de9e2)

**Comment by pankona** [comment]
@kachick 
AI と銘打ってそれはさすがに渋いのではw

**Comment by kachick** [comment]
https://github.com/coderabbitai/coderabbit-docs/blob/652dd227d9c7a80cfda6507d23d70dcabee71ea1/static/schema/schema.v2.json#L275-L701 この config schema で各種ツールを有効無効の切り替えができる。パット見全部 default true っぽいので、やはり実態としては mega linter を chat AI で wrap した感じなのでは
