### ISSUE TITLE
entering ikukyu

### ISSUE THREAD

**Issue by pankona** [pankona/pankona.github.com#224]
育休に入った

育休に入ったので軽く日記をつけておく。2024年2月から育休に入った。5月のゴールデンウィーク明けくらいまでを予定している。

第一子のときは育休をとらなかった。妻が「育休？おめー料理もできねえくせに休んで何をするつもりだ？働けおらー？」という意見だったのでな…。まあわからんではない。しかし今回は上の子の面倒を見る必要もあり、よしんば料理ができなかったとて休む価値がありそうと認めてもらうことができた。多少はできるけどな？お味噌汁くらいは作れる。

第二子はいまのところ2024年2月中旬くらいに生まれてくるような予定ではある。あと2週間後くらい。が、どうも妻の様子を見ているとなんとなく早まるような気がする。妻は医者から「あと一週間くらい安静にしといてくれ」と言われている。安静ってなに、今にもこぼれそうってことなのかい？とはいえ2024年2月1日現在、経過週数的にも子の体重的にもいつ生まれてもいいような段にはなりつつあるので、多少早まったとてもはやそれほど問題ではないようだ。まあゆっくりしていてくれよ。そんな急いで出てきたってしょうがないぞ。

社会人になってから、大手を振って数ヶ月休むというのはこれが初めてのことかもしれない (大手を振らずに休んだことはある)。育休明けにちゃんと社会復帰できるか今から不安である。育休初日はあっちこっち買い物に出掛けて終了した。妻は安静だっていって身動きが取れないもんだからね。さっそく育休の意味が出ているような気がしないでもない。

子が生まれてからは忙しくなりそうである。忙しいというか、きっとみんな寝不足になるんでうまく交代交代に眠れるようにあれこれ調整するみたいなやつである。第二子なので勝手はなんとなくわかっているつもりであるが、しかしね、子には個性があるからね。同じようにいくとは思わないほうがいいかしらね。気合い入れすぎてへばらないようにしよう。

胎教に良いことを信じて尾崎豊を歌ってあげている。15の夜。

**Comment by pankona** [comment]
プルリク2個できたんだが…？ @kachick

**Comment by kachick** [comment]
おめでとうございます！ 👶 

二人目を祝福すべくPRも2つできちゃったんじゃない？ハッハー

みたいにアメリカンな事を書き込もうかと思ったんですが、一応PR出しては見ました https://github.com/pankona/pankona.github.com/pull/228
