### ISSUE TITLE
chatgpt generated cooking 2024 03 04

### ISSUE THREAD

**Issue by pankona** [pankona/pankona.github.com#261]
豚肉とキャベツと人参をコンソメスープで煮たもの

突然の料理ログ

![PXL_20240303_082838594](https://github.com/pankona/pankona.github.com/assets/6533008/c7c82e7d-ca47-4169-9e57-fd7cbae9ba8f)
完成したところ

## 材料

- キャベツ：約200g（ざく切り）
- にんじん：1本（細切り）
- たまねぎ：1/2個（スライス）
- 豚肉（または鶏肉）：200g（一口大に切る）
- コンソメ：1個（固形の場合）または大さじ1（顆粒の場合）
- 水：200mlサラダ油：大さじ1
- 醤油（お好みで）：少々
- 塩・胡椒：適宜

## 作り方

- フライパンにサラダ油を熱し、お肉を炒める。お肉に焼き色がついたら一旦取り出しておく。
- 同じフライパンに、キャベツ、にんじん、たまねぎを加え、しんなりとするまで炒める。野菜がしんなりしたら、お肉を戻し入れる。
- 水とコンソメを加え、軽く煮込む。この時、お好みで醤油を少々加えてもいいよ。
- 塩・胡椒で味を調える。
- すべてがよく混ざり合い、味がなじんだら完成！

## 作った/食べた感想

- レシピは ChatGPT に聞いた。だいたい「キャベツとコンソメがあるぞ！」とだけ伝えたら上のようなレシピが提示された。
- キャベツと人参を切ったところで MP を使い切ったのでタマネギの参入は見送った。
- 味噌汁も作っておよそ一時間かかった。タイパは微妙か
- 味見した感じでは味が薄かった。醤油を2さじくらい足したらまあまあの味になったけどコンソメというよりは醤油味になった。コンソメスープで煮る？という部分のやり方が "なってない" のかもしれない。
- そもそも「煮る」という行為は栄養を摂取するという観点では好まれないらしい (Refs: [勝間式 超ロジカル家事](https://www.amazon.co.jp/gp/aw/d/B0793PRS7G))
  - ので、煮るのをやめろって話しもワンチャンある
  - コンソメ味で蒸す、ってできるものか？
- あと「炒める」という工程は、完全に人間をブロックする (人間がフライパンに張り付いてないといけない) ので、その間に何かをやるってのが難しい。非同期で行える何かをスタートしてから (味噌汁の湯を沸かすとか) 炒めものに入るほうがリソース効率が良さそう。
- とはいえ家族からの評判はまあまあだった。熟練して半分の時間で作れるならまたやっても良いかも。
  - 素材をカットするだけで 30 分近くかかっているので、なんかこう、トントントントンーン！って出来るようになればもっと早く済みそうではある

**Comment by pankona** [comment]
@kachick 
ブログコンセプト無視シリーズです。よろしくお願いします

**Comment by pankona** [comment]
絶対連載しなそうだけど、料理ラベルを作っておいた

**Comment by kachick** [comment]
俺のほうが料理スキルたけぇはずだぜ！

とメラメラ謎の嫉妬が湧いてたけど、自分が作るのは全部茶色くなるからカラフルさの時点で負けた感が強い

**Comment by pankona** [comment]
なるほど彩りね。
キャベツ、にんじん、たまねぎという候補からキャベツとにんじんが選ばれたのは「運」でしかないからね。運が味方したかもしれねえ
