### ISSUE TITLE
xiaomi pad 6

### ISSUE THREAD

**Issue by pankona** [pankona/pankona.github.com#293]
Xiaomi Pad 6 という Android タブレットを買ってみた

最近は目がかすむのでデカいスマホじみたものが欲しかったんじゃよ

## ひさびさに Android タブレット

ということで Android なタブレットを購入してみた。5万円そこそこの Xiaomi Pad 6 である。いわゆる中華タブレットであるが、少なくともカタログ上はそれなりにハイスペックであり、YouTube なんかを調べた限りにおいてはまあまあ評判も良さそうな一品である。利用目的はツイッター見たり Kindle 見たりちょっとウェブをさまよってみたりと、かるーい使い方をする想定である。Xiaomi Pad 6 はむしろこのユースケースに対しては過剰スペックとも言えるかもしれない。

以下、半日ほど使ってみた感想。

## Kindle は快適だしツイッターもまあまあ快適

Kindle は大画面で文字が読めるので大変よい。これだけで買ってよかった感ある。特にオライリーの技術書みたいな固定レイアウトの本がしっかり読めるというのが大きい。雑誌も読めるぞ…！

ツイッターはタブレットに最適化された UI じゃなくてスマホと同じ見た目がデカい画面に広がるだけであることを知った。まあそれはそれで見やすいから良いんだけど、もうちょっとこう、タブレットのデカさを活かした UI であってほしかった。ツイッターのタブレット向けは何年もこういう UI なのかな？だったらもはやこれから対応されるのも望み薄なのかもしれないね。

## 外付けキーボードでの入力はやや不便

Android タブレットに外付けキーボードをつなぐことでなんちゃって PC っぽい環境を構築することをちょっと期待していた。実際に外付けキーボードをつないでみたところ、まあまあちゃんと動く。ちゃんと動くんだけども、どうやら入力切り替え (日本語と直接入力を切り替えるやつ) をはじめとして、いろいろあんまり気持ちよく入力できない要素があることが分かってきた。
- まず入力のためのアプリ (GBoard やら ATOK やら Simeji やら) によって外付けキーボード接続時の入力切り替えのやり方が結構異なる。Shift+Space だったり Alt+Space だったり ` 一発だったりする。どのアプリがどういう振る舞いをするのかは実際に触って確かめないといけなくて面倒極まりない。しかもだいたいキーコンフィグ変えられない。俺は Ctrl+Space 派なんだが？
- Simeji は画面にソフトウェアキーボードを出しておかないと、外付けキーボードによる入力切り替えが効かない。そんなことある…？不便極まりないと言わざるを得ない
  - すぐアンインストールした
- これらはいずれも Capslock を Ctrl に変える設定がない。
  - ちなみに外付けキーボードの Capslock の振る舞いを変更することだけを目的にしたアプリが存在する。Capslock を Ctrl に変えたかったらこの手のアプリを入れるのもアリ。
- Shift 押しながらカーソルキー押してテキストの範囲選択とかやりたくなることあると思うんだけど、そういう PC でよくある機能はないようだ。これもまあまあ不便である。
  - もうすこし検証してみたところ、どうやら Shift 押しながら左右のキーを押す分には範囲選択ができるようだ。一方、Shift 押しながら上下キーはダメっぽい。
- ESC キーが ESC 以外の振る舞いをする。ブラウザバックになったり ` になったりする。なんとかいい感じの設定ならないか模索したがそもそも大した設定項目がない。いろいろいじくってみたものの、結局絶対に ESC っぽい振る舞いだけはしてくれなかった。なんで？

そんなわけで、何か書き物をするっていうときにはおとなしく使い慣れた PC でやるのが丸いということを思い知った。とはいえ Surface Go みたいなものを選ぶと今度はタッチでの操作が不愉快になりそうでね。なかなかままならぬものである。Windows 版の Kindle アプリがだいぶ渋いという一面もある。

## Vim でコードを書くのは快適

GitHub Codespaces に ssh で侵入し、Vim を用いたコーディングを行うというのが最近の自分の開発スタイルである。このやり方をする分には入力切り替えも ESC もそこまで登場しないので不便を感じにくい。範囲選択も Vim の機能を使えば済む。やっぱ Vim なんだよな

## ブログを書くのもやれんことはない

外付けキーボードを用いた入力まわりについて先述のような不満があるものの、とはいえやはり外付けキーボードはフリック入力をするより何倍も速く文字を入力できる。快適。しかしやや特殊な入力環境な気もしていて、慣れてしまうと普段の業務に影響してしまうかもしれない…。しかしまあ ESC だけはまともに効いてほしかった。それ以外は大丈夫。

この記事もひとまず Xiaomi Pad + 外付けキーボードで書いてみた。スマホではここまで長いものを書く気にはならなかっただろう。うむ、やれんことはない。不満はあるが悪くはない。

**Comment by kachick** [comment]
Pixel Tablet との比較検討記事をお願いします
