### ISSUE TITLE
introduce dishwasher part 1

### ISSUE THREAD

**Issue by pankona** [pankona/pankona.github.com#322]
食洗機を導入しようとしているがゴールまでの道のりが長すぎる

令和における家電の「三種の神器」のひとつであるところの食洗機を導入しようとしている。令和における家電の三種の神器というのは、衣類乾燥器、ロボット掃除機、そして食洗機であるらしい。へぇー

Amazonだかビックカメラだかで発注して設置してもらってハイ終了、やったね！ってなる想定だったのだが、なかなかこの食洗機、入れるまでが大変そうなことが分かってきた。長いバトルになりそうなので、バトルログを書いていく。連載である。

## 食洗機を入れたい理由

2024年2月に子が生まれたこともあり、家事をちょっとでも時短したいという欲望が自分にも妻にも出てきたというのが端的な理由である。あと冬場は洗い物で手が荒れるみたいな地味に鬱陶しい現象を回避したいという理由もある。

## 食洗機の「タイプ」を選ぶ

結論からすると我が家には「置くタイプの食洗機」しかチョイスできないことが分かってきた。

食洗機には置くタイプとビルトインするタイプがある。デカい食洗機がほしい。ちまちま洗っていたんじゃ逆に不便になりそうな気がしているためである。デカいのがいいんだ。するとビルトインが良いっていう話になりそうである。ビルトイン、つまりキッチンまわりの「引き出し」がそのまま食洗機になっちまうというやり方である。概ね、置くタイプより容量が大きい。

しかし後付けのビルトイン食洗機なんて導入可能か？という疑問があった。やれたとしてもそれなりに工事が必要かも？ということで東京ガスの方においでいただいて「我が家のキッチンにいまからビルトインの食洗機が入れられるか？」というのをジャッジしてもらった。結果は「NG」。ビルトイン食洗機は大きさの企画がだいたい決まっていて、それに収まるような引き出しがついてなければ導入不可能であるとのこと。我が家のキッチンの引き出しはなんかやたらデカかった。ビルトイン食洗機には不適合。まあ分かる。理解した。やむなし。

ということで置くタイプの食洗機から選択しよう、ということになった。東京ガスの方にはお帰りいただいた。ありがとう。

## 置くタイプの食洗機を入れるにも色々ある

置くタイプの食洗機をチョイスしていく。置くタイプの食洗機にも色々タイプがある。水をどこから調達するか、というので「タンク式」と「水栓から取る式」が存在する。タンクを使うやつは前もって水を補充しておいた状態で食洗機を動かす。水栓から水を取るやつは、使うときに自動的に水を調達してくれる。後者のほうが世話なしである。当然後者のものを選ぶことをファーストチョイスとしていく。

## 分岐水栓がつけられない蛇口

さて、水栓から取るってどういうことか。これは典型的には「水道の蛇口の根本のあたりにアタッチメントをつけて、水を分岐できるようにする」というやり方で実現するようだ。これを実現するためのアイテムが「分岐水栓」と呼ばれるブツである。これを購入して蛇口にくっつけることで (ちょっと工事じみたことをする)、水道を二股に分けられるようにするという寸法。

ただ、分岐水栓というのも色々あって、我が家で使っている蛇口に適合するものを調達しないといけない。蛇口の型番を入れると適合する分岐水栓を探してくれるサイト (https://sumai.panasonic.jp/dishwasher/bunki/search.html) なんかもあったりする。

それで、実はこの世の中には「適合する分岐水栓がない蛇口」というものが存在している。どうも我が家の蛇口、現存する分岐水栓で適合するものが存在しない模様である。先述の Panasonic のサイトを使ってみたり、ナニワ製作所さん (分岐水栓を作っている製造メーカー) に問い合わせてみたり、なんなら蛇口 (いまさらだが正式には水栓金具と呼ぶ) の販売者であるところのクリナップさんにも問い合わせてみたりしたので、それなりの確度の情報だと思う。手は尽くした。

ちなみにシンクに穴をあけて水栓コンセントを導入するというやり方もあるようだが、ちょうどいい感じに穴を開ける場所がないので、こっちのやり方はいったん考えていない。

## 電源もなんかしないといけない

食洗機を導入するためには「アース付きコンセント」が必要であるようだ。しかし食洗機を置きたい場所の近辺にはアース付きのコンセントがない。つまり？コンセントをアース付きにするような工事が別途必要になるっていうことな気がしている。っていうかそもそも食洗機を置きたい場所の近くにコンセントがないのだが？コンセントを増やす必要があるんでは？

## つまり何が必要なのか

我が家に食洗機を導入するまでには、以下の工程が必要そうである。

- 蛇口を分岐水栓を導入可能なものに取り替える (要工事)
- 分岐水栓を導入する (要工事)
- アース付きコンセントを設える (要工事)
- 食洗機を置く

3つは工事が必要そうか。大変すぎない？どんだけ時間かかるんだろ。タンク式、充電式、みたいな食洗機を使えばこのへんの工事は省略できるのだが面倒な日常にはしたくないし……。工事はそれぞれ業者が異なる可能性もありそうで、たいへん面倒そうな雰囲気が漂っている気がしている。長い目でみたらガチで導入しておくべきか。うーむ。

食洗機そのものはビックカメラで (ポイントを使いつつ) 購入しようと思っていた。ので、それにかかる工事もなんとなくビックカメラさんにお願いしようと思っていた。いったん「現場」を見てもらってお見積りをお願いして、ついでに蛇口のまわりもどうにかしてくれないか聞いてみようと思う。たぶん蛇口をどうにかするのはサポート対象外な気がしないでもない。お見積りは来週の週末に予約した。予想外にすんなり入ってくれることを願ってやまない。

つづく

**Comment by pankona** [comment]
こんなん書く前に技術書典に新刊を出した話を書けばよかったかもしれねえ

**Comment by pankona** [comment]
@kachick レビューお願いします（？）

**Comment by kachick** [comment]
レビューってこの issue 内でやるべきなのかbotがだしてきたPR側でやるべきなのか。

PR側の方がレビューはしやすそうだけど、Authorが修正しやすいのかがよくわかっていない

**Comment by kachick** [comment]
TOKEN使って本人アカウントから送ってきてる事になってるからPR側で良さげだ

**Comment by pankona** [comment]
@kachick どっちでも！
